# Generated by Django 4.2.16 on 2024-09-10 16:12

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfPlannedTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('descriptions', ckeditor.fields.RichTextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('DeparturePlace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Place.Tour_set+', to='travel.place')),
                ('album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.album')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameofhotel', models.CharField(max_length=200)),
                ('descriptions', ckeditor.fields.RichTextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.album')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Place.Tour_set+', to='travel.place')),
            ],
        ),
    ]
