# Generated by Django 4.2.16 on 2024-09-11 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_selfplannedtour_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='vaitro',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Admin', 'Admin')], default='Customer', max_length=30),
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
