# Generated by Django 4.2.16 on 2024-09-11 09:28

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_alter_user_vaitro_delete_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DatePost', models.DateTimeField(auto_now_add=True)),
                ('DateUpdate', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=5000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DatePost', models.DateTimeField(auto_now_add=True)),
                ('DateUpdate', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=1000)),
                ('content', ckeditor.fields.RichTextField()),
                ('active', models.BooleanField(default=True)),
                ('album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.album')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
