# Generated by Django 4.2.16 on 2024-09-11 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_tag_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DatePost', models.DateTimeField(auto_now_add=True)),
                ('DateUpdate', models.DateTimeField(auto_now=True)),
                ('OneOrReturn', models.BooleanField(default=True)),
                ('Quantity_Adult', models.IntegerField(default=1)),
                ('Quantity_Children', models.IntegerField(default=0)),
                ('SeatClass', models.CharField(choices=[('Economy_class', 'Economy Class'), ('Business_class', 'Business Class'), ('Complete_class', 'First Class')], default='Economy_class', max_length=30)),
                ('DeparturePlace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Place.Tour_set+', to='travel.place')),
                ('DepartureTime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Schedule.Tour_set+', to='travel.schedule')),
                ('Destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Schedule.Tour_set+', to='travel.place')),
                ('EstimatedTime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Schedule.Tour_set+', to='travel.schedule')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.transport')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='SelfPlannedTour',
        ),
    ]
