# Generated by Django 4.2.16 on 2024-09-11 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_bookticket_delete_selfplannedtour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cmt_news',
            old_name='imageCMTNews',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='cmt_tour',
            old_name='imageCMTTour',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='rating_tour',
            old_name='NumberOfStart',
            new_name='NumberOfStar',
        ),
    ]
