# Generated by Django 4.2.16 on 2024-09-13 15:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0010_room_hotel_alter_bookhotel_checkin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookhotel',
            name='Checkin',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 13, 22, 17, 2, 675779)),
        ),
        migrations.AlterField(
            model_name='bookhotel',
            name='Checkout',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 13, 22, 17, 2, 675779)),
        ),
        migrations.CreateModel(
            name='HotelRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Price', models.FloatField()),
                ('id_hotel', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='travel.hotel')),
                ('id_room', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='travel.room')),
            ],
        ),
    ]
