# Generated by Django 4.2.16 on 2024-09-19 02:47

import cloudinary.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0012_alter_bookhotel_checkin_alter_bookhotel_checkout_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookhotel',
            name='Checkin',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 19, 9, 47, 49, 109958)),
        ),
        migrations.AlterField(
            model_name='bookhotel',
            name='Checkout',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 19, 9, 47, 49, 109958)),
        ),
        migrations.AlterField(
            model_name='image',
            name='Path',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
