# Generated by Django 4.2.16 on 2024-09-20 01:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0014_remove_album_image_id_image_album_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookhotel',
            name='user_book',
        ),
        migrations.AlterField(
            model_name='bookhotel',
            name='Checkin',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 20, 8, 16, 59, 345296)),
        ),
        migrations.AlterField(
            model_name='bookhotel',
            name='Checkout',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 20, 8, 16, 59, 345296)),
        ),
        migrations.AlterField(
            model_name='bookhotel',
            name='id_user_book_hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Admin.bookhotel_set+', to='travel.admin'),
        ),
    ]
