# Generated by Django 4.2.16 on 2024-09-20 01:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0015_remove_bookhotel_user_book_alter_bookhotel_checkin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='user_post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='travel.customer'),
        ),
        migrations.AlterField(
            model_name='bookhotel',
            name='Checkin',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 20, 8, 38, 20, 152677)),
        ),
        migrations.AlterField(
            model_name='bookhotel',
            name='Checkout',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 20, 8, 38, 20, 152677)),
        ),
        migrations.AlterField(
            model_name='bookhotel',
            name='id_user_book_hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Admin.bookhotel_set+', to='travel.customer'),
        ),
        migrations.AlterField(
            model_name='bookticket',
            name='user_book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='travel.customer'),
        ),
        migrations.AlterField(
            model_name='like_news',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.customer'),
        ),
        migrations.AlterField(
            model_name='like_tour',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.customer'),
        ),
        migrations.AlterField(
            model_name='rating_tour',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.customer'),
        ),
    ]
