# Generated by Django 4.2.16 on 2024-09-20 04:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0018_remove_schedule_datepost_remove_schedule_dateupdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookhotel',
            name='Checkin',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 20, 11, 25, 48, 359398)),
        ),
        migrations.AlterField(
            model_name='bookhotel',
            name='Checkout',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 20, 11, 25, 48, 359398)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='DepartureDay',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='DepartureTime',
            field=models.TimeField(),
        ),
    ]
