# Generated by Django 4.2.16 on 2024-09-20 04:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0019_alter_bookhotel_checkin_alter_bookhotel_checkout_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportCar',
            fields=[
                ('transport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='travel.transport')),
                ('seat', models.IntegerField(null=True)),
            ],
            bases=('travel.transport',),
        ),
        migrations.CreateModel(
            name='TransportPLane',
            fields=[
                ('transport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='travel.transport')),
                ('TotalSeat', models.IntegerField(null=True)),
                ('EconomySeat', models.IntegerField(null=True)),
                ('BusinessSeat', models.IntegerField(null=True)),
                ('FirstSeat', models.IntegerField(null=True)),
            ],
            bases=('travel.transport',),
        ),
        migrations.RemoveField(
            model_name='transport',
            name='Seat',
        ),
        migrations.AlterField(
            model_name='bookhotel',
            name='Checkin',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 20, 11, 38, 57, 47759)),
        ),
        migrations.AlterField(
            model_name='bookhotel',
            name='Checkout',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 20, 11, 38, 57, 47759)),
        ),
        migrations.AlterField(
            model_name='bookticket',
            name='SeatClass',
            field=models.CharField(choices=[('Economy_class', 'Economy Class'), ('Business_class', 'Business Class'), ('First_class', 'First Class')], default='Economy_class', max_length=30),
        ),
    ]
