# Generated by Django 4.2.16 on 2024-09-20 05:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0020_transportcar_transportplane_remove_transport_seat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DepartureDay', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DepartureTime', models.TimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='bookhotel',
            name='Checkin',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 20, 12, 22, 43, 352816)),
        ),
        migrations.AlterField(
            model_name='bookhotel',
            name='Checkout',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 20, 12, 22, 43, 352816)),
        ),
        migrations.AlterField(
            model_name='bookticket',
            name='DepartureTime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ScheduleTime.Tour_set+', to='travel.scheduletime'),
        ),
        migrations.AlterField(
            model_name='bookticket',
            name='EstimatedTime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ScheduleTime.Tour_set+', to='travel.scheduletime'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='DepartureDay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ScheduleDay.Tour_set+', to='travel.scheduleday'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='DepartureTime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ScheduleTime.Tour_set+', to='travel.scheduletime'),
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
