# Generated by Django 4.2.16 on 2024-09-20 05:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0021_scheduleday_scheduletime_alter_bookhotel_checkin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookhotel',
            name='Checkin',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 20, 12, 25, 44, 130511)),
        ),
        migrations.AlterField(
            model_name='bookhotel',
            name='Checkout',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 20, 12, 25, 44, 130511)),
        ),
        migrations.AlterField(
            model_name='tour',
            name='DepartureDay',
            field=models.DateField(),
        ),
        migrations.DeleteModel(
            name='ScheduleDay',
        ),
    ]
