# Generated by Django 4.2.16 on 2024-09-20 06:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0022_alter_bookhotel_checkin_alter_bookhotel_checkout_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookhotel',
            name='Checkin',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 20, 13, 32, 24, 748563)),
        ),
        migrations.AlterField(
            model_name='bookhotel',
            name='Checkout',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 20, 13, 32, 24, 748563)),
        ),
        migrations.AlterField(
            model_name='bookhotel',
            name='Room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.hotelroom'),
        ),
    ]
