# Generated by Django 4.2.16 on 2024-09-21 15:54

import cloudinary.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0023_alter_bookhotel_checkin_alter_bookhotel_checkout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='cover',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bookhotel',
            name='Checkin',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 21, 22, 54, 31, 310301)),
        ),
        migrations.AlterField(
            model_name='bookhotel',
            name='Checkout',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 21, 22, 54, 31, 310301)),
        ),
    ]
