# Generated by Django 4.2.16 on 2024-09-23 23:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0024_tour_cover_alter_bookhotel_checkin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookhotel',
            name='Checkin',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 24, 6, 17, 35, 664472)),
        ),
        migrations.AlterField(
            model_name='bookhotel',
            name='Checkout',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 24, 6, 17, 35, 664472)),
        ),
        migrations.AlterField(
            model_name='booktour',
            name='id_customer_bt',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='travel.customer'),
        ),
        migrations.AlterField(
            model_name='booktour',
            name='id_tour_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='travel.tour'),
        ),
    ]
