# Generated by Django 4.2.16 on 2024-09-26 14:46

import ckeditor.fields
import cloudinary.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0026_alter_bookhotel_checkin_alter_bookhotel_checkout_and_more'),
    ]

    operations = [

        migrations.AlterField(
            model_name='bookhotel',
            name='Checkin',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 26, 21, 46, 25, 715238)),
        ),
        migrations.AlterField(
            model_name='bookhotel',
            name='Checkout',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 26, 21, 46, 25, 715238)),
        ),
        migrations.CreateModel(
            name='CMT_Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DatePost', models.DateTimeField(auto_now_add=True)),
                ('DateUpdate', models.DateTimeField(auto_now=True)),
                ('content', ckeditor.fields.RichTextField()),
                ('image', cloudinary.models.CloudinaryField(max_length=255, null=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='travel.blog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Like_Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Active', models.BooleanField(default=False)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='travel.blog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.customer')),
            ],
            options={
                'unique_together': {('blog', 'user')},
            },
        ),
    ]
