# Generated by Django 4.2.16 on 2024-09-27 03:44

import cloudinary.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0027_tour_cover_alter_bookhotel_checkin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='admin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='travel.admin'),
        ),
        migrations.AlterField(
            model_name='bookhotel',
            name='Checkin',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 27, 10, 44, 43, 461542)),
        ),
        migrations.AlterField(
            model_name='bookhotel',
            name='Checkout',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 27, 10, 44, 43, 461542)),
        ),
        migrations.AlterField(
            model_name='tour',
            name='cover',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True),
        ),
    ]
