# Generated by Django 4.2.16 on 2024-10-01 01:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0028_news_admin_alter_bookhotel_checkin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.album'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='user_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.customer'),
        ),
        migrations.AlterField(
            model_name='bookhotel',
            name='Checkin',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 1, 8, 52, 13, 663826)),
        ),
        migrations.AlterField(
            model_name='bookhotel',
            name='Checkout',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 1, 8, 52, 13, 663826)),
        ),
        migrations.AlterField(
            model_name='bookticket',
            name='Destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Place.Tour_set+', to='travel.place'),
        ),

    ]
